import type { Book } from '../interfaces/Book';

/**
 * Initial state of books, the data will not be used after the app is loaded;
 * Since it is persisted with the pinia-persist plugin.
 */
export const INITIAL_BOOKS: Book[] = [
  {
    id: 1,
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    genre: 'Fiction',
    year: 1960,
    isFav: false,
  },
  {
    id: 2,
    title: '1984',
    author: 'George Orwell',
    genre: 'Fiction',
    year: 1949,
    isFav: true,
  },
  {
    id: 3,
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    genre: 'Fiction',
    year: 1925,
    isFav: false,
  },
  {
    id: 4,
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    genre: 'Fiction',
    year: 1813,
    isFav: false,
  },
  {
    id: 5,
    title: 'To the Lighthouse',
    author: 'Virginia Woolf',
    genre: 'Fiction',
    year: 1927,
    isFav: false,
  },
  {
    id: 6,
    title: 'Moby-Dick',
    author: 'Herman Melville',
    genre: 'Fiction',
    year: 1851,
    isFav: false,
  },
  {
    id: 7,
    title: 'The Catcher in the Rye',
    author: 'J.D. Salinger',
    genre: 'Fiction',
    year: 1951,
    isFav: true,
  },
  {
    id: 8,
    title: 'The Lord of the Rings',
    author: 'J.R.R. Tolkien',
    genre: 'Fantasy',
    year: 1954,
    isFav: true,
  },
  {
    id: 9,
    title: "Harry Potter and the Sorcerer's Stone",
    author: 'J.K. Rowling',
    genre: 'Fantasy',
    year: 1997,
    isFav: true,
  },
  {
    id: 10,
    title: 'The Hobbit',
    author: 'J.R.R. Tolkien',
    genre: 'Fantasy',
    year: 1937,
    isFav: true,
  },
  {
    id: 11,
    title: 'The Alchemist',
    author: 'Paulo Coelho',
    genre: 'Fiction',
    year: 1988,
    isFav: true,
  },
  {
    id: 12,
    title: 'The Chronicles of Narnia',
    author: 'C.S. Lewis',
    genre: 'Fantasy',
    year: 1950,
    isFav: false,
  },
  {
    id: 13,
    title: 'Brave New World',
    author: 'Aldous Huxley',
    genre: 'Fiction',
    year: 1932,
    isFav: false,
  },
  {
    id: 14,
    title: 'The Picture of Dorian Gray',
    author: 'Oscar Wilde',
    genre: 'Fiction',
    year: 1890,
    isFav: true,
  },
  {
    id: 15,
    title: 'The Odyssey',
    author: 'Homer',
    genre: 'Epic Poetry',
    year: -800,
    isFav: false,
  },
  {
    id: 16,
    title: 'The Divine Comedy',
    author: 'Dante Alighieri',
    genre: 'Epic Poetry',
    year: 1320,
    isFav: true,
  },
  {
    id: 17,
    title: 'Crime and Punishment',
    author: 'Fyodor Dostoevsky',
    genre: 'Fiction',
    year: 1866,
    isFav: false,
  },
  {
    id: 18,
    title: 'The Brothers Karamazov',
    author: 'Fyodor Dostoevsky',
    genre: 'Fiction',
    year: 1880,
    isFav: true,
  },
  {
    id: 19,
    title: 'The Little Prince',
    author: 'Antoine de Saint-Exupéry',
    genre: "Children's Literature",
    year: 1943,
    isFav: true,
  },
  {
    id: 20,
    title: 'The Hobbit',
    author: 'J.R.R. Tolkien',
    genre: 'Fantasy',
    year: 1937,
    isFav: true,
  },
  {
    id: 21,
    title: 'The Lord of the Rings',
    author: 'J.R.R. Tolkien',
    genre: 'Fantasy',
    year: 1954,
    isFav: true,
  },
  {
    id: 22,
    title: 'Harry Potter and the Chamber of Secrets',
    author: 'J.K. Rowling',
    genre: 'Fantasy',
    year: 1998,
    isFav: true,
  },
  {
    id: 23,
    title: 'Harry Potter and the Prisoner of Azkaban',
    author: 'J.K. Rowling',
    genre: 'Fantasy',
    year: 1999,
    isFav: true,
  },
  {
    id: 24,
    title: 'Harry Potter and the Goblet of Fire',
    author: 'J.K. Rowling',
    genre: 'Fantasy',
    year: 2000,
    isFav: true,
  },
  {
    id: 25,
    title: 'Harry Potter and the Order of the Phoenix',
    author: 'J.K. Rowling',
    genre: 'Fantasy',
    year: 2003,
    isFav: true,
  },
  {
    id: 26,
    title: 'Harry Potter and the Half-Blood Prince',
    author: 'J.K. Rowling',
    genre: 'Fantasy',
    year: 2005,
    isFav: true,
  },
  {
    id: 27,
    title: 'Harry Potter and the Deathly Hallows',
    author: 'J.K. Rowling',
    genre: 'Fantasy',
    year: 2007,
    isFav: true,
  },
  {
    id: 28,
    title: 'The Hunger Games',
    author: 'Suzanne Collins',
    genre: 'Science Fiction',
    year: 2008,
    isFav: true,
  },
  {
    id: 29,
    title: 'Catching Fire',
    author: 'Suzanne Collins',
    genre: 'Science Fiction',
    year: 2009,
    isFav: true,
  },
  {
    id: 30,
    title: 'Mockingjay',
    author: 'Suzanne Collins',
    genre: 'Science Fiction',
    year: 2010,
    isFav: true,
  },
];
